//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOTReminder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FirstAlertMinutes {
            get {
                return ((int)(this["FirstAlertMinutes"]));
            }
            set {
                this["FirstAlertMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SecondAlertMinutes {
            get {
                return ((int)(this["SecondAlertMinutes"]));
            }
            set {
                this["SecondAlertMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ThirdAlertMinutes {
            get {
                return ((int)(this["ThirdAlertMinutes"]));
            }
            set {
                this["ThirdAlertMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\DailyTimes.xlsx\"")]
        public string ExcelFilePath {
            get {
                return ((string)(this["ExcelFilePath"]));
            }
            set {
                this["ExcelFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFirstRun {
            get {
                return ((bool)(this["IsFirstRun"]));
            }
            set {
                this["IsFirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlertOnShabbos {
            get {
                return ((bool)(this["AlertOnShabbos"]));
            }
            set {
                this["AlertOnShabbos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int VisualAlertMinutes {
            get {
                return ((int)(this["VisualAlertMinutes"]));
            }
            set {
                this["VisualAlertMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EOS1FirstAlertPath {
            get {
                return ((string)(this["EOS1FirstAlertPath"]));
            }
            set {
                this["EOS1FirstAlertPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EOS1SecondAlertPath {
            get {
                return ((string)(this["EOS1SecondAlertPath"]));
            }
            set {
                this["EOS1SecondAlertPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EOS2FirstAlertPath {
            get {
                return ((string)(this["EOS2FirstAlertPath"]));
            }
            set {
                this["EOS2FirstAlertPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EOS2SecondAlertPath {
            get {
                return ((string)(this["EOS2SecondAlertPath"]));
            }
            set {
                this["EOS2SecondAlertPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int FirstAlertTefilaMinutes {
            get {
                return ((int)(this["FirstAlertTefilaMinutes"]));
            }
            set {
                this["FirstAlertTefilaMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SecondAlertTefilaMinutes {
            get {
                return ((int)(this["SecondAlertTefilaMinutes"]));
            }
            set {
                this["SecondAlertTefilaMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EOT2FirstAlertPath {
            get {
                return ((string)(this["EOT2FirstAlertPath"]));
            }
            set {
                this["EOT2FirstAlertPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EOT2SecondAlertPath {
            get {
                return ((string)(this["EOT2SecondAlertPath"]));
            }
            set {
                this["EOT2SecondAlertPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SunSetTenMin {
            get {
                return ((bool)(this["SunSetTenMin"]));
            }
            set {
                this["SunSetTenMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SunSetThreeMin {
            get {
                return ((bool)(this["SunSetThreeMin"]));
            }
            set {
                this["SunSetThreeMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SunSet {
            get {
                return ((bool)(this["SunSet"]));
            }
            set {
                this["SunSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SunSetTenPath {
            get {
                return ((string)(this["SunSetTenPath"]));
            }
            set {
                this["SunSetTenPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SunSetThreePath {
            get {
                return ((string)(this["SunSetThreePath"]));
            }
            set {
                this["SunSetThreePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SunSetPath {
            get {
                return ((string)(this["SunSetPath"]));
            }
            set {
                this["SunSetPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int SlideshowActivationIntervalSeconds {
            get {
                return ((int)(this["SlideshowActivationIntervalSeconds"]));
            }
            set {
                this["SlideshowActivationIntervalSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int SlideshowReturnIntervalSeconds {
            get {
                return ((int)(this["SlideshowReturnIntervalSeconds"]));
            }
            set {
                this["SlideshowReturnIntervalSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SlideshowImageDisplaySeconds {
            get {
                return ((int)(this["SlideshowImageDisplaySeconds"]));
            }
            set {
                this["SlideshowImageDisplaySeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Fade\"")]
        public string SlideshowTransitionType {
            get {
                return ((string)(this["SlideshowTransitionType"]));
            }
            set {
                this["SlideshowTransitionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string SlideshowImagesFolder {
            get {
                return ((string)(this["SlideshowImagesFolder"]));
            }
            set {
                this["SlideshowImagesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Welcome — Slideshow\"")]
        public string SlideshowHeaderText {
            get {
                return ((string)(this["SlideshowHeaderText"]));
            }
            set {
                this["SlideshowHeaderText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SlideshowEnabled {
            get {
                return ((bool)(this["SlideshowEnabled"]));
            }
            set {
                this["SlideshowEnabled"] = value;
            }
        }
    }
}
